sudo: false
dist: trusty
language: node_js

jobs:
  include:
    - stage: npm release
      deploy:
        tags: true
        provider: npm
        email: $LOGN_PUBLISH
        api_key: $TOKEN_PUBLISH
